<?php

function dna_menu() {
    $items = array();
    $items['dna_start'] = array(
        'title' => 'DNA Module',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('dna_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['dna_results'] = array(
        'title' => 'Results',
        'page callback' => 'dna_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function dna_form() {
    $form['dna_input'] = array(
        '#title' => 'DNA input',
        '#type' => 'textfield',
        '#description' => t('Enter DNA letter (A,C,G,T)'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Submit',
    );
    return $form;
}

function dna_find($input) {
    $output = array();
    $input = array($input);
    if($input == 'A') {
      array_push($output, 'T');
    }
    return $output;
}
