<?php

function dna_menu() {
    $items = array();
    $items['dna_start'] = array(
        'title' => 'DNA Module',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('dna_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['dna_results'] = array(
        'title' => 'Results',
        'page callback' => 'dna_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function dna_form() {
    $form['dna_input'] = array(
        '#title' => 'DNA input',
        '#type' => 'textfield',
        '#description' => t('Enter DNA letter sequence using the letters A,C,G,T. No punctuation or spaces.'),
        '#required' => TRUE,
        '#element_validate' => array('element_validate_acgt_input'),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Submit',
    );
    return $form;
}

function element_validate_acgt_input($element) {
    $user_input = strtoupper($element['#value']);
    $user_input = str_split($user_input);
    foreach($user_input as $input) {
        if(($input != 'A') && ($input != 'C') && ($input != 'G') && ($input != 'T')) {
          form_set_error('dna_input', 'Invalid character(s) submitted.');
        }
    }
}

function dna_find($input) {
    $output = array();
    $input = array($input);
    if($input == 'A') {
      array_push($output, 'T');
    }
    return $output;
}
